[theme]
# The preset Streamlit theme that your custom theme inherits from.
# Can be "light" or "dark".
base = "light"

# Primary accent color for interactive elements.
primaryColor = "#3b82f6"  # A modern blue

# Background color for the main content area.
backgroundColor = "#ffffff"  # Pure white for light mode

# Background color for sidebar and most interactive widgets.
secondaryBackgroundColor = "#f1f5f9" # A very light, cool gray

# Color used for almost all text.
textColor = "#0f172a" # A dark, slate gray for high contrast

# Font family for all text in the app.
# Can be "serif", "sans serif", or "monospace".
font = "sans serif"

[server]
# This helps in running the app smoothly.
headless = true
enableCORS = false